let a = {
    "message":
        "success", "code":
        0, "data":
        {
            "diseaseDataTotal":
                [{"id": "1", "name": "某些传染病和寄生虫病", "dataNum": 3601675776}, {
                    "id": "2",
                    "name": "肿瘤",
                    "dataNum": 2653106944
                }, {"id": "3", "name": "血液及造血器官疾病", "dataNum": 3965834752}, {
                    "id": "4",
                    "name": "内分泌、营养和代谢疾病",
                    "dataNum": 3249065472
                }, {"id": "5", "name": "精神和行为障碍", "dataNum": 3872107008}, {
                    "id": "6",
                    "name": "精神系统疾病",
                    "dataNum": 2865467904
                }, {"id": "7", "name": "眼和附器疾病", "dataNum": 3517221376}, {
                    "id": "8",
                    "name": "耳和乳突疾病",
                    "dataNum": 2190297600
                }, {"id": "9", "name": "循环系统疾病", "dataNum": 2908943104}, {
                    "id": "10",
                    "name": "呼吸系统疾病",
                    "dataNum": 2354592768
                }, {"id": "11", "name": "消化系统疾病", "dataNum": 3039474176}, {
                    "id": "12",
                    "name": "皮肤和皮下组织疾病",
                    "dataNum": 3206614016
                }, {"id": "13", "name": "肌肉骨骼系统和结缔组织疾病", "dataNum": 3543065856}, {
                    "id": "14",
                    "name": "泌尿生殖系统疾病",
                    "dataNum": 3432799232
                }, {"id": "15", "name": "妊辰分娩和产褥期", "dataNum": 2969920000}, {
                    "id": "16",
                    "name": "起源于围生期的某些情况",
                    "dataNum": 3535427840
                }, {"id": "17", "name": "先天性畸形、变形和染色体异常", "dataNum": 2135107840}, {
                    "id": "18",
                    "name": "症状体征和临床与实验室异常",
                    "dataNum": 3165245440
                }, {"id": "19", "name": "损伤、中毒和外因的某些其他后果", "dataNum": 2372421632}, {
                    "id": "20",
                    "name": "疾病和死亡的外因",
                    "dataNum": 2536460800
                }, {"id": "21", "name": "影响健康状态和与保健机构接触的因素", "dataNum": 3245462784}], "medicineDataTotal":
                [{"id": "1", "name": "消化系统及代谢药", "dataNum": 2818799616}, {
                    "id": "2",
                    "name": "血液和造血系统药物",
                    "dataNum": 3054750720
                }, {"id": "3", "name": "心血管系统药物", "dataNum": 2360201984}, {
                    "id": "4",
                    "name": "皮肤病用药",
                    "dataNum": 3949337600
                }, {"id": "5", "name": "生殖泌尿系统和性激素类药物", "dataNum": 3354044416}, {
                    "id": "6",
                    "name": "全身用激素类制剂(不含性激素)",
                    "dataNum": 2629736448
                }, {"id": "7", "name": "全身用抗感染药物", "dataNum": 3792460800}, {
                    "id": "8",
                    "name": "抗肿瘤和免疫调节剂",
                    "dataNum": 2447547392
                }, {"id": "9", "name": "肌肉骨骼系统", "dataNum": 3064717568}, {
                    "id": "10",
                    "name": "神经系统药物",
                    "dataNum": 2503905280
                }, {"id": "11", "name": "抗寄生虫药、杀虫剂和驱虫剂", "dataNum": 3845146880}, {
                    "id": "12",
                    "name": "呼吸系统用药",
                    "dataNum": 2367883520
                }, {"id": "13", "name": "感觉系统药物", "dataNum": 2603670272}, {
                    "id": "14",
                    "name": "杂类",
                    "dataNum": 2927693312
                }, {"id": "15", "name": "原料药及非直接作用于人体药物", "dataNum": 2454418432}], "districtPlusHospital":
                [{
                    "id": 1,
                    "districtId": 1,
                    "districtOrgNum": 350102,
                    "districtName": "鼓楼区",
                    "districtLatitude": 26.097900390625,
                    "districtLongitude": 119.29100036621094,
                    "districtDataNum": 3.559374174E9,
                    "hospitalName": "福建省福州儿童医院",
                    "hospitalLatitude": 26.078809,
                    "hospitalLongitude": 119.310852,
                    "hospitalDataNum": 7.8972350154E8,
                    "bedDataNum": 700,
                    "archivePeople": 1618994,
                    "medicineTotalUsage": 26515951,
                    "medicineTotalFee": 338797068
                }, {
                    "id": 2,
                    "districtId": 1,
                    "districtOrgNum": 350102,
                    "districtName": "鼓楼区",
                    "districtLatitude": 26.097900390625,
                    "districtLongitude": 119.29100036621094,
                    "districtDataNum": null,
                    "hospitalName": "福建医科大学孟超肝胆医院（原福州市传染病医院）",
                    "hospitalLatitude": 26.091194,
                    "hospitalLongitude": 119.287613,
                    "hospitalDataNum": 7.3134888015E8,
                    "bedDataNum": 746,
                    "archivePeople": 579956,
                    "medicineTotalUsage": 15721795,
                    "medicineTotalFee": 156153785
                }, {
                    "id": 3,
                    "districtId": 1,
                    "districtOrgNum": 350102,
                    "districtName": "鼓楼区",
                    "districtLatitude": 26.097900390625,
                    "districtLongitude": 119.29100036621094,
                    "districtDataNum": null,
                    "hospitalName": "福州市第七医院",
                    "hospitalLatitude": 26.085073,
                    "hospitalLongitude": 119.307143,
                    "hospitalDataNum": 5.3951260734E8,
                    "bedDataNum": 389,
                    "archivePeople": 392105,
                    "medicineTotalUsage": 169895370,
                    "medicineTotalFee": 148980387
                }, {
                    "id": 4,
                    "districtId": 1,
                    "districtOrgNum": 350102,
                    "districtName": "鼓楼区",
                    "districtLatitude": 26.097900390625,
                    "districtLongitude": 119.29100036621094,
                    "districtDataNum": null,
                    "hospitalName": "福州市皮肤病防治院",
                    "hospitalLatitude": 26.091187,
                    "hospitalLongitude": 119.2905,
                    "hospitalDataNum": 2.8491186405E8,
                    "bedDataNum": 350,
                    "archivePeople": 1862822,
                    "medicineTotalUsage": 63571478,
                    "medicineTotalFee": 194755493
                }, {
                    "id": 5,
                    "districtId": 1,
                    "districtOrgNum": 350102,
                    "districtName": "鼓楼区",
                    "districtLatitude": 26.097900390625,
                    "districtLongitude": 119.29100036621094,
                    "districtDataNum": null,
                    "hospitalName": "福州市中医院",
                    "hospitalLatitude": 26.096274,
                    "hospitalLongitude": 119.308964,
                    "hospitalDataNum": 1.21387732092E9,
                    "bedDataNum": 608,
                    "archivePeople": 674833,
                    "medicineTotalUsage": 1045753525,
                    "medicineTotalFee": 318169599
                }, {
                    "id": 6,
                    "districtId": 2,
                    "districtOrgNum": 350103,
                    "districtName": "台江区",
                    "districtLatitude": 26.06220054626465,
                    "districtLongitude": 119.3239974975586,
                    "districtDataNum": 5.17225305174E9,
                    "hospitalName": "福州市第二医院",
                    "hospitalLatitude": 26.052373,
                    "hospitalLongitude": 119.32719,
                    "hospitalDataNum": 2.75824096581E9,
                    "bedDataNum": 2233,
                    "archivePeople": 2783941,
                    "medicineTotalUsage": 848953394,
                    "medicineTotalFee": 2924269489
                }, {
                    "id": 7,
                    "districtId": 2,
                    "districtOrgNum": 350103,
                    "districtName": "台江区",
                    "districtLatitude": 26.06220054626465,
                    "districtLongitude": 119.3239974975586,
                    "districtDataNum": null,
                    "hospitalName": "福州市第一医院",
                    "hospitalLatitude": 26.065826,
                    "hospitalLongitude": 119.319233,
                    "hospitalDataNum": 2.41401208593E9,
                    "bedDataNum": 1955,
                    "archivePeople": 2005022,
                    "medicineTotalUsage": 867725424,
                    "medicineTotalFee": 2263969223
                }, {
                    "id": 8,
                    "districtId": 3,
                    "districtOrgNum": 350104,
                    "districtName": "仓山区",
                    "districtLatitude": 26.019699096679688,
                    "districtLongitude": 119.33499908447266,
                    "districtDataNum": 2.1952804443E9,
                    "hospitalName": "福建省福州结核病防治院",
                    "hospitalLatitude": 26.031624,
                    "hospitalLongitude": 119.303627,
                    "hospitalDataNum": 1.45471995276E9,
                    "bedDataNum": 870,
                    "archivePeople": 2549509,
                    "medicineTotalUsage": 149205214,
                    "medicineTotalFee": 849646940
                }, {
                    "id": 9,
                    "districtId": 3,
                    "districtOrgNum": 350104,
                    "districtName": "仓山区",
                    "districtLatitude": 26.019699096679688,
                    "districtLongitude": 119.33499908447266,
                    "districtDataNum": null,
                    "hospitalName": "福州神经精神病防治院",
                    "hospitalLatitude": 26.031767,
                    "hospitalLongitude": 119.297431,
                    "hospitalDataNum": 7.4056049154E8,
                    "bedDataNum": 900,
                    "archivePeople": 242248,
                    "medicineTotalUsage": 128483657,
                    "medicineTotalFee": 376589956
                }, {
                    "id": 10,
                    "districtId": 4,
                    "districtOrgNum": 350111,
                    "districtName": "晋安区",
                    "districtLatitude": 26.221799850463867,
                    "districtLongitude": 119.31500244140625,
                    "districtDataNum": 1.37185565112E9,
                    "hospitalName": "福州市第八医院",
                    "hospitalLatitude": 26.113855,
                    "hospitalLongitude": 119.3288,
                    "hospitalDataNum": 9.1196379E7,
                    "bedDataNum": 550,
                    "archivePeople": 244344,
                    "medicineTotalUsage": 20639971,
                    "medicineTotalFee": 25971925
                }, {
                    "id": 11,
                    "districtId": 4,
                    "districtOrgNum": 350111,
                    "districtName": "晋安区",
                    "districtLatitude": 26.221799850463867,
                    "districtLongitude": 119.31500244140625,
                    "districtDataNum": null,
                    "hospitalName": "福州市第六医院",
                    "hospitalLatitude": 26.071341,
                    "hospitalLongitude": 119.320908,
                    "hospitalDataNum": 9.744384972E7,
                    "bedDataNum": 388,
                    "archivePeople": 144379,
                    "medicineTotalUsage": 49864020,
                    "medicineTotalFee": 46391265
                }, {
                    "id": 12,
                    "districtId": 4,
                    "districtOrgNum": 350111,
                    "districtName": "晋安区",
                    "districtLatitude": 26.221799850463867,
                    "districtLongitude": 119.31500244140625,
                    "districtDataNum": null,
                    "hospitalName": "福州市妇幼保健院",
                    "hospitalLatitude": 26.079119,
                    "hospitalLongitude": 119.326752,
                    "hospitalDataNum": 1.1947078407E8,
                    "bedDataNum": 300,
                    "archivePeople": 451441,
                    "medicineTotalUsage": 19756843,
                    "medicineTotalFee": 68509876
                }, {
                    "id": 13,
                    "districtId": 4,
                    "districtOrgNum": 350111,
                    "districtName": "晋安区",
                    "districtLatitude": 26.221799850463867,
                    "districtLongitude": 119.31500244140625,
                    "districtDataNum": null,
                    "hospitalName": "福州市晋安区医院",
                    "hospitalLatitude": 26.074336,
                    "hospitalLongitude": 119.342631,
                    "hospitalDataNum": 1.06374463833E9,
                    "bedDataNum": 400,
                    "archivePeople": 1338336,
                    "medicineTotalUsage": 239618122,
                    "medicineTotalFee": 481663031
                }, {
                    "id": 14,
                    "districtId": 5,
                    "districtOrgNum": 350105,
                    "districtName": "马尾区",
                    "districtLatitude": 26.082599639892578,
                    "districtLongitude": 119.51100158691406,
                    "districtDataNum": 5.7584546145E8,
                    "hospitalName": "马尾区医院(福州经济技术开发区医院)",
                    "hospitalLatitude": 26.000284,
                    "hospitalLongitude": 119.463891,
                    "hospitalDataNum": 5.7584546145E8,
                    "bedDataNum": 475,
                    "archivePeople": 479310,
                    "medicineTotalUsage": 188647010,
                    "medicineTotalFee": 363982348
                }, {
                    "id": 15,
                    "districtId": 6,
                    "districtOrgNum": 350182,
                    "districtName": "长乐区",
                    "districtLatitude": 25.91550064086914,
                    "districtLongitude": 119.37799835205078,
                    "districtDataNum": 8.6901058398E8,
                    "hospitalName": "长乐区第二医院",
                    "hospitalLatitude": 25.985179,
                    "hospitalLongitude": 119.624739,
                    "hospitalDataNum": 2.8195102008E8,
                    "bedDataNum": 380,
                    "archivePeople": 378667,
                    "medicineTotalUsage": 158746057,
                    "medicineTotalFee": 144898834
                }, {
                    "id": 16,
                    "districtId": 6,
                    "districtOrgNum": 350182,
                    "districtName": "长乐区",
                    "districtLatitude": 25.91550064086914,
                    "districtLongitude": 119.37799835205078,
                    "districtDataNum": null,
                    "hospitalName": "长乐区妇幼保健院",
                    "hospitalLatitude": 25.966593,
                    "hospitalLongitude": 119.520213,
                    "hospitalDataNum": 1.3762137753E8,
                    "bedDataNum": 450,
                    "archivePeople": 621429,
                    "medicineTotalUsage": 21721008,
                    "medicineTotalFee": 79324256
                }, {
                    "id": 17,
                    "districtId": 6,
                    "districtOrgNum": 350182,
                    "districtName": "长乐区",
                    "districtLatitude": 25.91550064086914,
                    "districtLongitude": 119.37799835205078,
                    "districtDataNum": null,
                    "hospitalName": "长乐区医院",
                    "hospitalLatitude": 25.965318,
                    "hospitalLongitude": 119.526777,
                    "hospitalDataNum": 3.6701272101E8,
                    "bedDataNum": 971,
                    "archivePeople": 533875,
                    "medicineTotalUsage": 207941380,
                    "medicineTotalFee": 330156483
                }, {
                    "id": 18,
                    "districtId": 6,
                    "districtOrgNum": 350182,
                    "districtName": "长乐区",
                    "districtLatitude": 25.91550064086914,
                    "districtLongitude": 119.37799835205078,
                    "districtDataNum": null,
                    "hospitalName": "长乐区中医院",
                    "hospitalLatitude": 25.963391,
                    "hospitalLongitude": 119.531304,
                    "hospitalDataNum": 8.242546536E7,
                    "bedDataNum": 278,
                    "archivePeople": 185094,
                    "medicineTotalUsage": 129657801,
                    "medicineTotalFee": 117850765
                }, {
                    "id": 19,
                    "districtId": 7,
                    "districtOrgNum": 350181,
                    "districtName": "福清市",
                    "districtLatitude": 25.638099670410156,
                    "districtLongitude": 119.76599884033203,
                    "districtDataNum": 2.17438458663E9,
                    "hospitalName": "福清市第二医院",
                    "hospitalLatitude": 25.617233,
                    "hospitalLongitude": 119.466894,
                    "hospitalDataNum": 1.6450431435E8,
                    "bedDataNum": 432,
                    "archivePeople": 74523,
                    "medicineTotalUsage": 51024083,
                    "medicineTotalFee": 137332216
                }, {
                    "id": 20,
                    "districtId": 7,
                    "districtOrgNum": 350181,
                    "districtName": "福清市",
                    "districtLatitude": 25.638099670410156,
                    "districtLongitude": 119.76599884033203,
                    "districtDataNum": null,
                    "hospitalName": "福清市第三医院",
                    "hospitalLatitude": 25.705716,
                    "hospitalLongitude": 119.319619,
                    "hospitalDataNum": 2.9384872491E8,
                    "bedDataNum": 376,
                    "archivePeople": 345647,
                    "medicineTotalUsage": 139924269,
                    "medicineTotalFee": 125877348
                }, {
                    "id": 21,
                    "districtId": 7,
                    "districtOrgNum": 350181,
                    "districtName": "福清市",
                    "districtLatitude": 25.638099670410156,
                    "districtLongitude": 119.76599884033203,
                    "districtDataNum": null,
                    "hospitalName": "福清市妇幼保健院",
                    "hospitalLatitude": 25.713828,
                    "hospitalLongitude": 119.356184,
                    "hospitalDataNum": 1.4497990053E8,
                    "bedDataNum": 580,
                    "archivePeople": 573776,
                    "medicineTotalUsage": 23678910,
                    "medicineTotalFee": 78877165
                }, {
                    "id": 22,
                    "districtId": 7,
                    "districtOrgNum": 350181,
                    "districtName": "福清市",
                    "districtLatitude": 25.638099670410156,
                    "districtLongitude": 119.76599884033203,
                    "districtDataNum": null,
                    "hospitalName": "福清市皮肤病防治院",
                    "hospitalLatitude": 25.730041,
                    "hospitalLongitude": 119.373832,
                    "hospitalDataNum": 1.4439399147E8,
                    "bedDataNum": 220,
                    "archivePeople": 97723,
                    "medicineTotalUsage": 68889470,
                    "medicineTotalFee": 105315146
                }, {
                    "id": 23,
                    "districtId": 7,
                    "districtOrgNum": 350181,
                    "districtName": "福清市",
                    "districtLatitude": 25.638099670410156,
                    "districtLongitude": 119.76599884033203,
                    "districtDataNum": null,
                    "hospitalName": "福清市医院",
                    "hospitalLatitude": 25.735229,
                    "hospitalLongitude": 119.352193,
                    "hospitalDataNum": 1.31487537177E9,
                    "bedDataNum": 911,
                    "archivePeople": 2638497,
                    "medicineTotalUsage": 55458673,
                    "medicineTotalFee": 382551251
                }, {
                    "id": 24,
                    "districtId": 7,
                    "districtOrgNum": 350181,
                    "districtName": "福清市",
                    "districtLatitude": 25.638099670410156,
                    "districtLongitude": 119.76599884033203,
                    "districtDataNum": null,
                    "hospitalName": "福清市中医院",
                    "hospitalLatitude": 25.731382,
                    "hospitalLongitude": 119.390437,
                    "hospitalDataNum": 1.117822836E8,
                    "bedDataNum": 280,
                    "archivePeople": 207858,
                    "medicineTotalUsage": 138171055,
                    "medicineTotalFee": 121144297
                }, {
                    "id": 25,
                    "districtId": 8,
                    "districtOrgNum": 350121,
                    "districtName": "闽侯县",
                    "districtLatitude": 26.18239974975586,
                    "districtLongitude": 119.12200164794922,
                    "districtDataNum": 5.5670739978E8,
                    "hospitalName": "闽侯县人民医院",
                    "hospitalLatitude": 25.903253,
                    "hospitalLongitude": 119.383132,
                    "hospitalDataNum": 2.7564367596E8,
                    "bedDataNum": 390,
                    "archivePeople": 467712,
                    "medicineTotalUsage": 169923675,
                    "medicineTotalFee": 409586674
                }, {
                    "id": 26,
                    "districtId": 8,
                    "districtOrgNum": 350121,
                    "districtName": "闽侯县",
                    "districtLatitude": 26.18239974975586,
                    "districtLongitude": 119.12200164794922,
                    "districtDataNum": null,
                    "hospitalName": "闽侯县医院",
                    "hospitalLatitude": 26.152866,
                    "hospitalLongitude": 119.167055,
                    "hospitalDataNum": 2.8106372382E8,
                    "bedDataNum": 530,
                    "archivePeople": 500373,
                    "medicineTotalUsage": 189745030,
                    "medicineTotalFee": 395098167
                }, {
                    "id": 27,
                    "districtId": 9,
                    "districtOrgNum": 350122,
                    "districtName": "连江县",
                    "districtLatitude": 26.301599502563477,
                    "districtLongitude": 119.56800079345703,
                    "districtDataNum": 1.03706927262E9,
                    "hospitalName": "连江县医院",
                    "hospitalLatitude": 26.200608,
                    "hospitalLongitude": 119.542557,
                    "hospitalDataNum": 7.0017457788E8,
                    "bedDataNum": 593,
                    "archivePeople": 785967,
                    "medicineTotalUsage": 209191537,
                    "medicineTotalFee": 493890942
                }, {
                    "id": 28,
                    "districtId": 9,
                    "districtOrgNum": 350122,
                    "districtName": "连江县",
                    "districtLatitude": 26.301599502563477,
                    "districtLongitude": 119.56800079345703,
                    "districtDataNum": null,
                    "hospitalName": "连江县中医院",
                    "hospitalLatitude": 26.209086,
                    "hospitalLongitude": 119.542153,
                    "hospitalDataNum": 3.3689469474E8,
                    "bedDataNum": 330,
                    "archivePeople": 271358,
                    "medicineTotalUsage": 307355390,
                    "medicineTotalFee": 165864096
                }, {
                    "id": 29,
                    "districtId": 10,
                    "districtOrgNum": 350123,
                    "districtName": "罗源县",
                    "districtLatitude": 26.50629997253418,
                    "districtLongitude": 119.46499633789062,
                    "districtDataNum": 8.0278923273E8,
                    "hospitalName": "罗源县妇幼保健院",
                    "hospitalLatitude": 26.492256,
                    "hospitalLongitude": 119.551063,
                    "hospitalDataNum": 1.2711647184E8,
                    "bedDataNum": 255,
                    "archivePeople": 549807,
                    "medicineTotalUsage": 20483967,
                    "medicineTotalFee": 60507654
                }, {
                    "id": 30,
                    "districtId": 10,
                    "districtOrgNum": 350123,
                    "districtName": "罗源县",
                    "districtLatitude": 26.50629997253418,
                    "districtLongitude": 119.46499633789062,
                    "districtDataNum": null,
                    "hospitalName": "罗源县医院",
                    "hospitalLatitude": 26.492159,
                    "hospitalLongitude": 119.555158,
                    "hospitalDataNum": 5.5694840187E8,
                    "bedDataNum": 650,
                    "archivePeople": 765375,
                    "medicineTotalUsage": 187227457,
                    "medicineTotalFee": 440692547
                }, {
                    "id": 31,
                    "districtId": 10,
                    "districtOrgNum": 350123,
                    "districtName": "罗源县",
                    "districtLatitude": 26.50629997253418,
                    "districtLongitude": 119.46499633789062,
                    "districtDataNum": null,
                    "hospitalName": "罗源县中医院",
                    "hospitalLatitude": 26.491956,
                    "hospitalLongitude": 119.552859,
                    "hospitalDataNum": 1.1872435902E8,
                    "bedDataNum": 265,
                    "archivePeople": 210369,
                    "medicineTotalUsage": 148975849,
                    "medicineTotalFee": 124987632
                }, {
                    "id": 32,
                    "districtId": 11,
                    "districtOrgNum": 350124,
                    "districtName": "闽清县",
                    "districtLatitude": 26.212299346923828,
                    "districtLongitude": 118.77899932861328,
                    "districtDataNum": 1.29037185537E9,
                    "hospitalName": "闽清精神病防治院",
                    "hospitalLatitude": 26.223786,
                    "hospitalLongitude": 118.877617,
                    "hospitalDataNum": 2.9943982155E8,
                    "bedDataNum": 560,
                    "archivePeople": 40723,
                    "medicineTotalUsage": 27912518,
                    "medicineTotalFee": 75127032
                }, {
                    "id": 33,
                    "districtId": 11,
                    "districtOrgNum": 350124,
                    "districtName": "闽清县",
                    "districtLatitude": 26.212299346923828,
                    "districtLongitude": 118.77899932861328,
                    "districtDataNum": null,
                    "hospitalName": "闽清县六都医院",
                    "hospitalLatitude": 26.114428,
                    "hospitalLongitude": 118.778613,
                    "hospitalDataNum": 5.084065734E7,
                    "bedDataNum": 487,
                    "archivePeople": 76559,
                    "medicineTotalUsage": 52481650,
                    "medicineTotalFee": 141177518
                }, {
                    "id": 34,
                    "districtId": 11,
                    "districtOrgNum": 350124,
                    "districtName": "闽清县",
                    "districtLatitude": 26.212299346923828,
                    "districtLongitude": 118.77899932861328,
                    "districtDataNum": null,
                    "hospitalName": "闽清县医院",
                    "hospitalLatitude": 26.224499,
                    "hospitalLongitude": 118.877428,
                    "hospitalDataNum": 5.2599409383E8,
                    "bedDataNum": 850,
                    "archivePeople": 593966,
                    "medicineTotalUsage": 190501820,
                    "medicineTotalFee": 415157281
                }, {
                    "id": 35,
                    "districtId": 11,
                    "districtOrgNum": 350124,
                    "districtName": "闽清县",
                    "districtLatitude": 26.212299346923828,
                    "districtLongitude": 118.77899932861328,
                    "districtDataNum": null,
                    "hospitalName": "闽清县中医院",
                    "hospitalLatitude": 26.231188,
                    "hospitalLongitude": 118.870002,
                    "hospitalDataNum": 4.1409728265E8,
                    "bedDataNum": 280,
                    "archivePeople": 296950,
                    "medicineTotalUsage": 157723178,
                    "medicineTotalFee": 175786683
                }, {
                    "id": 36,
                    "districtId": 12,
                    "districtOrgNum": 350125,
                    "districtName": "永泰县",
                    "districtLatitude": 25.85740089416504,
                    "districtLongitude": 118.79499816894531,
                    "districtDataNum": 5.0944700526E8,
                    "hospitalName": "永泰县医院",
                    "hospitalLatitude": 25.872741,
                    "hospitalLongitude": 118.935048,
                    "hospitalDataNum": 4.017560307E8,
                    "bedDataNum": 596,
                    "archivePeople": 378754,
                    "medicineTotalUsage": 169623841,
                    "medicineTotalFee": 386548921
                }, {
                    "id": 37,
                    "districtId": 12,
                    "districtOrgNum": 350125,
                    "districtName": "永泰县",
                    "districtLatitude": 25.85740089416504,
                    "districtLongitude": 118.79499816894531,
                    "districtDataNum": null,
                    "hospitalName": "永泰县中医院",
                    "hospitalLatitude": 25.868211,
                    "hospitalLongitude": 118.939793,
                    "hospitalDataNum": 1.0769097456E8,
                    "bedDataNum": 290,
                    "archivePeople": 199110,
                    "medicineTotalUsage": 128483656,
                    "medicineTotalFee": 105789054
                }, {
                    "id": 38,
                    "districtId": 13,
                    "districtOrgNum": 350128,
                    "districtName": "平潭县",
                    "districtLatitude": null,
                    "districtLongitude": null,
                    "districtDataNum": null,
                    "hospitalName": null,
                    "hospitalLatitude": null,
                    "hospitalLongitude": null,
                    "hospitalDataNum": null,
                    "bedDataNum": null,
                    "archivePeople": null,
                    "medicineTotalUsage": null,
                    "medicineTotalFee": null
                }, {
                    "id": 39,
                    "districtId": 13,
                    "districtOrgNum": 350128,
                    "districtName": "平潭县",
                    "districtLatitude": null,
                    "districtLongitude": null,
                    "districtDataNum": null,
                    "hospitalName": null,
                    "hospitalLatitude": null,
                    "hospitalLongitude": null,
                    "hospitalDataNum": null,
                    "bedDataNum": null,
                    "archivePeople": null,
                    "medicineTotalUsage": null,
                    "medicineTotalFee": null
                }], "hospitalOverall":
                [{
                    "patienrNum": 24333447,
                    "caseFatalityRate": "0.17",
                    "year": 2016,
                    "patientOut": 848621,
                    "hospitalBed": 30.4,
                    "patientNumByType": 24167877,
                    "patientIn": 850444
                }, {
                    "patienrNum": 24047991,
                    "caseFatalityRate": "0.11",
                    "year": 2017,
                    "patientOut": 901735,
                    "hospitalBed": 31.7,
                    "patientNumByType": 23905118,
                    "patientIn": 903944
                }], "healthPeople":
                [{
                    "year": 2016,
                    "healthBed": 4.75,
                    "hospitalBed": 3.86,
                    "doctorNum": 2.64,
                    "techPeople": 7.25,
                    "nurseNum": 3.14
                }, {
                    "year": 2017,
                    "healthBed": 4.84,
                    "hospitalBed": 4.01,
                    "doctorNum": 2.75,
                    "techPeople": 7.41,
                    "nurseNum": 3.24
                }], "platformDataTotal":
                [{"id": "1", "name": "公共卫生数据", "dataNum": 17851012682}, {
                    "id": "2",
                    "name": "临床数据",
                    "dataNum": 55684994566
                }, {"id": "3", "name": "基因组学数据", "dataNum": 7741661698}, {
                    "id": "4",
                    "name": "医学影像",
                    "dataNum": 4878094861
                }, {"id": "5", "name": "物联网数据", "dataNum": 7842239492}], "wordSummaryData":
                {
                    "overallStockData":
                        "200多亿条", "unStructuredData":
                        "130TB", "structuredData":
                        "10TB"
                }
            ,
            "wordSummary":
                [{
                    "version": "V2.2",
                    "words": "目前国家健康医疗大数据中心（福州）完成福州市37家二级及以上公立医疗机构的医疗数据、174个基层医疗卫生机构的数据汇聚工作（含HIS、EMR、LIS、PACS四大业务系统）。已入库结构化存量数据200多亿条，超10TB；非结构化数据130TB（X线、CT、MRI、B超、心电等）。制定元数据规范约10000条、数据字典超500个及近300个临床数据集。"
                }], "particularDiseases":
                {
                    "chronicBrochitis":
                        [{
                            "patientNum": 149,
                            "year": 2004,
                            "district": "鼓楼区",
                            "districtType": 2,
                            "districtNum": 916
                        }, {
                            "patientNum": 215,
                            "year": 2005,
                            "district": "台江区",
                            "districtType": 2,
                            "districtNum": 2750
                        }, {
                            "patientNum": 241,
                            "year": 2006,
                            "district": "仓山区",
                            "districtType": 2,
                            "districtNum": 446
                        }, {
                            "patientNum": 282,
                            "year": 2007,
                            "district": "晋安区",
                            "districtType": 2,
                            "districtNum": 399
                        }, {
                            "patientNum": 339,
                            "year": 2008,
                            "district": "马尾区",
                            "districtType": 2,
                            "districtNum": 78
                        }, {
                            "patientNum": 407,
                            "year": 2009,
                            "district": "长乐区",
                            "districtType": 2,
                            "districtNum": 34
                        }, {
                            "patientNum": 494,
                            "year": 2010,
                            "district": "福清市",
                            "districtType": 2,
                            "districtNum": 13
                        }, {
                            "patientNum": 780,
                            "year": 2011,
                            "district": "闽侯县",
                            "districtType": 2,
                            "districtNum": 284
                        }, {
                            "patientNum": 1527,
                            "year": 2012,
                            "district": "连江县",
                            "districtType": 2,
                            "districtNum": 101
                        }, {
                            "patientNum": 2519,
                            "year": 2013,
                            "district": "罗源县",
                            "districtType": 2,
                            "districtNum": 29
                        }, {
                            "patientNum": 2810,
                            "year": 2014,
                            "district": "闽清县",
                            "districtType": 2,
                            "districtNum": 45
                        }, {
                            "patientNum": 2926,
                            "year": 2015,
                            "district": "永泰县",
                            "districtType": 2,
                            "districtNum": 70
                        }, {
                            "patientNum": 2753,
                            "year": 2016,
                            "district": "平潭县",
                            "districtType": 2,
                            "districtNum": 20
                        }, {"patientNum": 2551, "year": 2017, "districtType": 2}], "coronary":
                        [{
                            "patientNum": 683,
                            "year": 2004,
                            "district": "鼓楼区",
                            "districtType": 1,
                            "districtNum": 2067
                        }, {
                            "patientNum": 1072,
                            "year": 2005,
                            "district": "台江区",
                            "districtType": 1,
                            "districtNum": 5116
                        }, {
                            "patientNum": 1249,
                            "year": 2006,
                            "district": "仓山区",
                            "districtType": 1,
                            "districtNum": 921
                        }, {
                            "patientNum": 1405,
                            "year": 2007,
                            "district": "晋安区",
                            "districtType": 1,
                            "districtNum": 954
                        }, {
                            "patientNum": 1612,
                            "year": 2008,
                            "district": "马尾区",
                            "districtType": 1,
                            "districtNum": 177
                        }, {
                            "patientNum": 1819,
                            "year": 2009,
                            "district": "长乐区",
                            "districtType": 1,
                            "districtNum": 14
                        }, {
                            "patientNum": 1983,
                            "year": 2010,
                            "district": "福清市",
                            "districtType": 1,
                            "districtNum": 50
                        }, {
                            "patientNum": 2292,
                            "year": 2011,
                            "district": "闽侯县",
                            "districtType": 1,
                            "districtNum": 464
                        }, {
                            "patientNum": 3337,
                            "year": 2012,
                            "district": "连江县",
                            "districtType": 1,
                            "districtNum": 159
                        }, {
                            "patientNum": 4406,
                            "year": 2013,
                            "district": "罗源县",
                            "districtType": 1,
                            "districtNum": 44
                        }, {
                            "patientNum": 4076,
                            "year": 2014,
                            "district": "闽清县",
                            "districtType": 1,
                            "districtNum": 48
                        }, {
                            "patientNum": 4115,
                            "year": 2015,
                            "district": "永泰县",
                            "districtType": 1,
                            "districtNum": 65
                        }, {
                            "patientNum": 4004,
                            "year": 2016,
                            "district": "平潭县",
                            "districtType": 1,
                            "districtNum": 34
                        }, {"patientNum": 4404, "year": 2017, "districtType": 1}]
                }
            ,
            "healthOverall":
                [{
                    "hospitalOrg": 230,
                    "year": 2016,
                    "healthOrg": 1995,
                    "healthTechPeople": 51703,
                    "healthBedNum": 33877,
                    "hospitalBed": 27554,
                    "doctorNum": 18841,
                    "nurseNum": 22373
                }, {
                    "hospitalOrg": 232,
                    "year": 2017,
                    "healthOrg": 1839,
                    "healthTechPeople": 53412,
                    "healthBedNum": 34878,
                    "hospitalBed": 28887,
                    "doctorNum": 19803,
                    "nurseNum": 23373
                }], "commonDiseases":
                [{
                    "rank": 4,
                    "diseaseName": "冠心病",
                    "patientNum": 10819,
                    "sampleNum": 400000,
                    "ratio": 0.027047,
                    "diseaseType": "非传染病",
                    "year": null
                }, {
                    "rank": 5,
                    "diseaseName": "恶性肿瘤",
                    "patientNum": 9792,
                    "sampleNum": 400000,
                    "ratio": 0.02448,
                    "diseaseType": "？",
                    "year": null
                }, {
                    "rank": 6,
                    "diseaseName": "慢性支气管炎",
                    "patientNum": 5855,
                    "sampleNum": 400000,
                    "ratio": 0.014637,
                    "diseaseType": "慢性非传染病",
                    "year": null
                }, {
                    "rank": 7,
                    "diseaseName": "哮喘",
                    "patientNum": 1940,
                    "sampleNum": 400000,
                    "ratio": 0.00485,
                    "diseaseType": "非传染病",
                    "year": null
                }, {
                    "rank": 8,
                    "diseaseName": "麻疹",
                    "patientNum": 1896,
                    "sampleNum": 400000,
                    "ratio": 0.00474,
                    "diseaseType": "传染病",
                    "year": null
                }, {
                    "rank": 9,
                    "diseaseName": "痛风",
                    "patientNum": 1288,
                    "sampleNum": 400000,
                    "ratio": 0.00322,
                    "diseaseType": "慢性非传染病",
                    "year": null
                }, {
                    "rank": 10,
                    "diseaseName": "脂肪肝",
                    "patientNum": 1122,
                    "sampleNum": 400000,
                    "ratio": 0.002805,
                    "diseaseType": "慢性非传染病",
                    "year": null
                }, {
                    "rank": 11,
                    "diseaseName": "肾炎",
                    "patientNum": 941,
                    "sampleNum": 400000,
                    "ratio": 0.002352,
                    "diseaseType": "慢性非传染病",
                    "year": null
                }, {
                    "rank": 12,
                    "diseaseName": "肝炎",
                    "patientNum": 811,
                    "sampleNum": 400000,
                    "ratio": 0.002027,
                    "diseaseType": "非传染病",
                    "year": null
                }, {
                    "rank": 13,
                    "diseaseName": "肝硬化",
                    "patientNum": 517,
                    "sampleNum": 400000,
                    "ratio": 0.001293,
                    "diseaseType": "慢性非传染病",
                    "year": null
                }, {
                    "rank": 14,
                    "diseaseName": "慢性阻塞性肺疾病",
                    "patientNum": 188,
                    "sampleNum": 400000,
                    "ratio": 4.7E-4,
                    "diseaseType": "非传染病",
                    "year": null
                }, {
                    "rank": 15,
                    "diseaseName": "手足口病",
                    "patientNum": 183,
                    "sampleNum": 400000,
                    "ratio": 4.58E-4,
                    "diseaseType": "传染病",
                    "year": null
                }, {
                    "rank": 16,
                    "diseaseName": "脑卒中",
                    "patientNum": 128,
                    "sampleNum": 400000,
                    "ratio": 3.2E-4,
                    "diseaseType": "非传染病",
                    "year": null
                }, {
                    "rank": 17,
                    "diseaseName": "白血病",
                    "patientNum": 54,
                    "sampleNum": 400000,
                    "ratio": 1.35E-4,
                    "diseaseType": "慢性非传染病",
                    "year": null
                }, {
                    "rank": 18,
                    "diseaseName": "结核病",
                    "patientNum": 40,
                    "sampleNum": 400000,
                    "ratio": 1.0E-4,
                    "diseaseType": "非传染病",
                    "year": null
                }, {
                    "rank": 19,
                    "diseaseName": "高血脂",
                    "patientNum": 26,
                    "sampleNum": 400000,
                    "ratio": 6.5E-5,
                    "diseaseType": "慢性非传染病",
                    "year": null
                }, {
                    "rank": 20,
                    "diseaseName": "脊柱侧弯",
                    "patientNum": 22,
                    "sampleNum": 400000,
                    "ratio": 5.5E-5,
                    "diseaseType": "非传染病",
                    "year": null
                }, {
                    "rank": 21,
                    "diseaseName": "慢性胰腺炎",
                    "patientNum": 22,
                    "sampleNum": 400000,
                    "ratio": 5.5E-5,
                    "diseaseType": "慢性非传染病",
                    "year": null
                }, {
                    "rank": 22,
                    "diseaseName": "慢性骨髓炎",
                    "patientNum": 19,
                    "sampleNum": 400000,
                    "ratio": 4.8E-5,
                    "diseaseType": "慢性非传染病",
                    "year": null
                }, {
                    "rank": 23,
                    "diseaseName": "伤寒",
                    "patientNum": 8,
                    "sampleNum": 400000,
                    "ratio": 2.0E-5,
                    "diseaseType": "传染病",
                    "year": null
                }, {
                    "rank": 24,
                    "diseaseName": "流感",
                    "patientNum": 7,
                    "sampleNum": 400000,
                    "ratio": 1.7E-5,
                    "diseaseType": "传染病",
                    "year": null
                }, {
                    "rank": 25,
                    "diseaseName": "霍乱",
                    "patientNum": 3,
                    "sampleNum": 400000,
                    "ratio": 8.0E-6,
                    "diseaseType": "传染病",
                    "year": null
                }, {
                    "rank": 26,
                    "diseaseName": "破伤风",
                    "patientNum": 2,
                    "sampleNum": 400000,
                    "ratio": 5.0E-6,
                    "diseaseType": "传染病",
                    "year": null
                }, {
                    "rank": 27,
                    "diseaseName": "重型精神疾病",
                    "patientNum": 0,
                    "sampleNum": 400000,
                    "ratio": 0.0,
                    "diseaseType": "非传染病",
                    "year": null
                }, {
                    "rank": 28,
                    "diseaseName": "先心病",
                    "patientNum": 0,
                    "sampleNum": 400000,
                    "ratio": 0.0,
                    "diseaseType": "非传染病",
                    "year": null
                }, {
                    "rank": 29,
                    "diseaseName": "疟疾",
                    "patientNum": 0,
                    "sampleNum": 400000,
                    "ratio": 0.0,
                    "diseaseType": "传染病",
                    "year": null
                }, {
                    "rank": 30,
                    "diseaseName": "丝虫病",
                    "patientNum": 0,
                    "sampleNum": 400000,
                    "ratio": 0.0,
                    "diseaseType": "传染病",
                    "year": null
                }, {
                    "rank": 31,
                    "diseaseName": "流行性腮腺炎",
                    "patientNum": 0,
                    "sampleNum": 400000,
                    "ratio": 0.0,
                    "diseaseType": "传染病",
                    "year": null
                }, {
                    "rank": 32,
                    "diseaseName": "猩红热",
                    "patientNum": 0,
                    "sampleNum": 400000,
                    "ratio": 0.0,
                    "diseaseType": "传染病",
                    "year": null
                }, {
                    "rank": 33,
                    "diseaseName": "百日咳",
                    "patientNum": 0,
                    "sampleNum": 400000,
                    "ratio": 0.0,
                    "diseaseType": "传染病",
                    "year": null
                }, {
                    "rank": 34,
                    "diseaseName": "慢性心律失常",
                    "patientNum": 0,
                    "sampleNum": 400000,
                    "ratio": 0.0,
                    "diseaseType": "慢性非传染病",
                    "year": null
                }, {
                    "rank": 1,
                    "diseaseName": "高血压",
                    "patientNum": 72652,
                    "sampleNum": 400000,
                    "ratio": 0.18163,
                    "diseaseType": "非传染病",
                    "year": null
                }, {
                    "rank": 2,
                    "diseaseName": "糖尿病",
                    "patientNum": 36252,
                    "sampleNum": 400000,
                    "ratio": 0.09063,
                    "diseaseType": "非传染病",
                    "year": null
                }, {
                    "rank": 3,
                    "diseaseName": "慢性胃炎",
                    "patientNum": 24352,
                    "sampleNum": 400000,
                    "ratio": 0.06088,
                    "diseaseType": "慢性非传染病",
                    "year": null
                }], "districtDataTotal":
                [{"id": "1", "name": "陕西", "dataNum": 5950611773}, {
                    "id": "2",
                    "name": "福建",
                    "dataNum": 20709586615
                }, {"id": "3", "name": "广东", "dataNum": 5348399}, {"id": "4", "name": "湖北", "dataNum": 139609329}, {
                    "id": "5",
                    "name": "四川",
                    "dataNum": 5344337
                }], "structuredDataset":
                [{
                    "secTotal": 5.3482411884E9,
                    "secModule": "公用业务",
                    "dataNumNew": 4.47342544E7,
                    "name": "一卡通挂号收费表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 5.3482411884E9,
                    "secModule": "公用业务",
                    "dataNumNew": 1.6292034E7,
                    "name": "医院职工基本信息",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 5.3482411884E9,
                    "secModule": "公用业务",
                    "dataNumNew": 4.81332401E8,
                    "name": "单据主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 5.3482411884E9,
                    "secModule": "公用业务",
                    "dataNumNew": 2.8389796556E9,
                    "name": "单据执行记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 5.3482411884E9,
                    "secModule": "公用业务",
                    "dataNumNew": 6.16881496E8,
                    "name": "单据明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 5.3482411884E9,
                    "secModule": "公用业务",
                    "dataNumNew": 2.67235826E7,
                    "name": "员工票据领用情况",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 5.3482411884E9,
                    "secModule": "公用业务",
                    "dataNumNew": 4.02355624E7,
                    "name": "患者卡信息",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 5.3482411884E9,
                    "secModule": "公用业务",
                    "dataNumNew": 3.07239438E7,
                    "name": "患者基本信息数据集",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 5.3482411884E9,
                    "secModule": "公用业务",
                    "dataNumNew": 3453168.4,
                    "name": "病人皮试记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 5.3482411884E9,
                    "secModule": "公用业务",
                    "dataNumNew": 1.224488892E8,
                    "name": "病人预交金记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 5.3482411884E9,
                    "secModule": "公用业务",
                    "dataNumNew": 5.940916168E8,
                    "name": "票据出入库主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 5.3482411884E9,
                    "secModule": "公用业务",
                    "dataNumNew": 3.78777498E7,
                    "name": "票据出入库明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 5.3482411884E9,
                    "secModule": "公用业务",
                    "dataNumNew": 4.745376482E8,
                    "name": "票据存储记录表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 5.3482411884E9,
                    "secModule": "公用业务",
                    "dataNumNew": 1.99291862E7,
                    "name": "转诊记录表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 2469885.0,
                    "name": "处方模板主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 3465464.2,
                    "name": "处方模板明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 22644.6,
                    "name": "急诊记录主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 1.44029963E8,
                    "name": "门诊处方主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 6234.8,
                    "name": "门诊处方审核主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 241857.0,
                    "name": "门诊处方审核明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 5.722430252E8,
                    "name": "门诊处方明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 1.031768628E8,
                    "name": "门诊挂号记录表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 1.83136118E7,
                    "name": "门诊死亡诊断报告",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 7.30036252E7,
                    "name": "门诊结算日志",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 5.26391008E7,
                    "name": "门诊结算记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 4.37498666E7,
                    "name": "门诊诊断报告",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 2.09598884E7,
                    "name": "门诊诊断记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 3527653.8,
                    "name": "门诊费用明细",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.0712504506E9,
                    "secModule": "门诊业务",
                    "dataNumNew": 3.34007674E7,
                    "name": "预约挂号记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 14077.8,
                    "name": "临床路径医嘱模板",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 5.27090982E7,
                    "name": "临床路径医嘱记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 278403.4,
                    "name": "临床路径变异情况记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 4.53502324E7,
                    "name": "临床路径执行记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 1.5386844E7,
                    "name": "临床路径执行评估",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 563818.2,
                    "name": "临床路径记录主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 157698.2,
                    "name": "临床路径记录主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 3401.2,
                    "name": "临床路径诊断字典",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 1.11780768E7,
                    "name": "临床路径费用统计",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 3.01397184E7,
                    "name": "住院会诊记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 5.0929725E7,
                    "name": "住院生产记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 3.66382478E7,
                    "name": "住院病人信息变动日志",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 583640.2,
                    "name": "住院病程记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 1.721310998E8,
                    "name": "住院结算主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 4.809378508E8,
                    "name": "住院结算明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 3.07036125E8,
                    "name": "住院诊断记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 3.0042276E7,
                    "name": "入出院评估",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 257875.2,
                    "name": "减免记录主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 4043307.4,
                    "name": "减免记录明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 5.81029504E7,
                    "name": "在科病人记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 6.213867E7,
                    "name": "患者住院信息",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 3177398.4,
                    "name": "担保批欠记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 4.436616756E8,
                    "name": "操作员发票结账明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 23071.4,
                    "name": "用药记录模板",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 2.13567552E7,
                    "name": "病人体征记录明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 125342.8,
                    "name": "病人延期住院信息",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 1341036.4,
                    "name": "病案首页",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 2.206117144E9,
                    "secModule": "住院业务",
                    "dataNumNew": 3.77808728E8,
                    "name": "预出院结算记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 1.29792938E7,
                    "name": "医生常用药品字典",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 34183.6,
                    "name": "抗菌药物申请记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 2.8011291E7,
                    "name": "摆药个人明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 343512.4,
                    "name": "摆药反馈（不成）记录细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 9.21234435E8,
                    "name": "摆药池",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 3.052683832E8,
                    "name": "摆药记录主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 1.808386052E8,
                    "name": "摆药记录明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 6.8242636E7,
                    "name": "摆药队列记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 6.907637E7,
                    "name": "科室药品主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 2.477847504E8,
                    "name": "科室药品明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 4.24191944E7,
                    "name": "药品出入库主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 1.220131154E8,
                    "name": "药品出入库明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 26875.2,
                    "name": "药品包装配置",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 1.21936232E7,
                    "name": "药品字典",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 8727994.0,
                    "name": "药品库存单元分发字典",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 4.823095992E8,
                    "name": "药品库存表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 1381292.0,
                    "name": "药品库存转移记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 5.397652458E8,
                    "name": "药品盘点主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 1.633378648E8,
                    "name": "药品盘点明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 4.6151325E7,
                    "name": "药品请领主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 2.70301482E7,
                    "name": "药品请领明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 2.969738508E8,
                    "name": "药品调价主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 7.12082206E8,
                    "name": "药品调价明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 1.29420511E8,
                    "name": "药品采购主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 2.233061996E8,
                    "name": "药品采购明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 4.74027884E7,
                    "name": "药品采购计划主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 4.01557684E7,
                    "name": "药品采购计划明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 1.3228956356E9,
                    "name": "退药记录主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.0753496848E9,
                    "secModule": "药品业务",
                    "dataNumNew": 2.39429872E7,
                    "name": "退药记录明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7.605936492E8,
                    "secModule": "医嘱业务",
                    "dataNumNew": 306097.0,
                    "name": "医嘱打印记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7.605936492E8,
                    "secModule": "医嘱业务",
                    "dataNumNew": 3.28389732E7,
                    "name": "医嘱明细日志",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7.605936492E8,
                    "secModule": "医嘱业务",
                    "dataNumNew": 3526448.2,
                    "name": "医嘱模板主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7.605936492E8,
                    "secModule": "医嘱业务",
                    "dataNumNew": 8041682.0,
                    "name": "医嘱模板明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7.605936492E8,
                    "secModule": "医嘱业务",
                    "dataNumNew": 8.92114014E7,
                    "name": "医嘱记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7.605936492E8,
                    "secModule": "医嘱业务",
                    "dataNumNew": 3.268527658E8,
                    "name": "医嘱记录池",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7.605936492E8,
                    "secModule": "医嘱业务",
                    "dataNumNew": 2.998162816E8,
                    "name": "非药品类医嘱收费明细",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 4.4939345E7,
                    "secModule": "检验业务",
                    "dataNumNew": 2529186.0,
                    "name": "LIS样本记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 4.4939345E7,
                    "secModule": "检验业务",
                    "dataNumNew": 3.31953952E7,
                    "name": "LIS检验记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 4.4939345E7,
                    "secModule": "检验业务",
                    "dataNumNew": 9214763.8,
                    "name": "LIS申请单",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 0.0,
                    "secModule": "检查业务",
                    "dataNumNew": 0.0,
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.9587379E8,
                    "secModule": "手术业务",
                    "dataNumNew": 1.004250038E8,
                    "name": "手术申请主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.9587379E8,
                    "secModule": "手术业务",
                    "dataNumNew": 9.54487864E7,
                    "name": "手术记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7267.0,
                    "secModule": "疾病预防",
                    "dataNumNew": 3652.0,
                    "name": "食源性疾病报告-暴露信息",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7267.0,
                    "secModule": "疾病预防",
                    "dataNumNew": 30.8,
                    "name": "食源性疾病报告-生物标本采集",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7267.0,
                    "secModule": "疾病预防",
                    "dataNumNew": 3583.8,
                    "name": "食源性疾病报告-病例基本信息",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 24.0,
                    "secModule": "不良反应",
                    "dataNumNew": 8.8,
                    "name": "药品不良反应报告主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 24.0,
                    "secModule": "不良反应",
                    "dataNumNew": 15.4,
                    "name": "药品不良反应报告明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 3.6639964E8,
                    "secModule": "输血业务",
                    "dataNumNew": 1.71391176E7,
                    "name": "用血申请记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 3.6639964E8,
                    "secModule": "输血业务",
                    "dataNumNew": 1.77785718E7,
                    "name": "血型确认记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 3.6639964E8,
                    "secModule": "输血业务",
                    "dataNumNew": 1.118840206E8,
                    "name": "血液保存主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 3.6639964E8,
                    "secModule": "输血业务",
                    "dataNumNew": 1.7211931E7,
                    "name": "血液保存明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 3.6639964E8,
                    "secModule": "输血业务",
                    "dataNumNew": 8947705.8,
                    "name": "血液字典",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 3.6639964E8,
                    "secModule": "输血业务",
                    "dataNumNew": 1.57514456E7,
                    "name": "血液库存记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 3.6639964E8,
                    "secModule": "输血业务",
                    "dataNumNew": 232980.0,
                    "name": "血液检测结果记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 3.6639964E8,
                    "secModule": "输血业务",
                    "dataNumNew": 211090.0,
                    "name": "血液检测记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 3.6639964E8,
                    "secModule": "输血业务",
                    "dataNumNew": 2.08114214E7,
                    "name": "输血主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 3.6639964E8,
                    "secModule": "输血业务",
                    "dataNumNew": 1.564313564E8,
                    "name": "输血明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 1082.4,
                    "name": "医用物资主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 1.97146092E7,
                    "name": "物资保存主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 1.907642E8,
                    "name": "物资保存明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 1.97336766E8,
                    "name": "物资出入库主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 1.901726178E8,
                    "name": "物资出入库日志",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 9.63405564E7,
                    "name": "物资出入库明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 1.0304305E7,
                    "name": "物资字典",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 1.676158506E8,
                    "name": "物资审核主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 2.92207212E7,
                    "name": "物资审核明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 8.07873638E7,
                    "name": "物资库存记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 8.21322018E7,
                    "name": "物资损溢记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 1.406307562E8,
                    "name": "物资收费记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 1.44614184E7,
                    "name": "物资请领主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 2.123797808E8,
                    "name": "物资请领明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 44849.2,
                    "name": "物资采购主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 151173.0,
                    "name": "物资采购明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 29449.2,
                    "name": "物资采购计划主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.4322021626E9,
                    "secModule": "医院耗材",
                    "dataNumNew": 114461.6,
                    "name": "物资采购计划明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.5906014E7,
                    "secModule": "床位业务",
                    "dataNumNew": 6.5710106E7,
                    "name": "床位使用记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.5906014E7,
                    "secModule": "床位业务",
                    "dataNumNew": 82997.2,
                    "name": "床位信息主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 6.5906014E7,
                    "secModule": "床位业务",
                    "dataNumNew": 112910.6,
                    "name": "床位收费配置表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7.36739786E8,
                    "secModule": "医院设备",
                    "dataNumNew": 6.358324764E8,
                    "name": "设备使用记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7.36739786E8,
                    "secModule": "医院设备",
                    "dataNumNew": 1.35951222E7,
                    "name": "设备出入库明细",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7.36739786E8,
                    "secModule": "医院设备",
                    "dataNumNew": 36568.4,
                    "name": "设备字典",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7.36739786E8,
                    "secModule": "医院设备",
                    "dataNumNew": 3.30014058E7,
                    "name": "设备库存记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7.36739786E8,
                    "secModule": "医院设备",
                    "dataNumNew": 2.36149452E7,
                    "name": "设备申请主表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7.36739786E8,
                    "secModule": "医院设备",
                    "dataNumNew": 3.06359856E7,
                    "name": "设备申请明细表",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 7.36739786E8,
                    "secModule": "医院设备",
                    "dataNumNew": 23282.6,
                    "name": "设备记录明细",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.8608912674E9,
                    "secModule": "医保业务",
                    "dataNumNew": 1.6315303246E9,
                    "name": "医保交易日志",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.8608912674E9,
                    "secModule": "医保业务",
                    "dataNumNew": 1.118680772E8,
                    "name": "医保登记记录",
                    "fstModule": "数据资源-临床数据"
                }, {
                    "secTotal": 1.8608912674E9,
                    "secModule": "医保业务",
                    "dataNumNew": 1.174928656E8,
                    "name": "医保结算明细",
                    "fstModule": "数据资源-临床数据"
                }]
        }
}
let b = {
    "message": "success",
    "code": 0,
    "data": [{"number": 37, "unit": "家", "title": "二级以上公立医院"}, {
        "number": 211,
        "unit": "个",
        "title": "对接医疗机构医疗数据"
    }, {"number": 700, "unit": "超700万人", "title": "覆盖人口"}, {
        "number": 10,
        "unit": "TB",
        "title": "已入库结构化存量数据"
    }, {"number": 130, "unit": "TB", "title": "非结构化数据"}, {"number": 200, "unit": "亿", "title": "总数据量"}, {
        "number": 300,
        "unit": "个",
        "title": "临床数据集"
    }, {"number": 500, "unit": "个", "title": "数据字典"}, {"number": 10000, "unit": "条", "title": "共制定元数据规范"}]
}